name: 'Commit history issue labeler'
description: 'Adds labels to all issues and PRs based on commit history between two given references'
author: 'Dimitri Lavrenük <dimitri.lavr@gmail.com>'
branding:
  icon: 'layers'
  color: 'purple'
inputs:
  from:
    description: 'Tag Name or Commit SHA to start commits from (not included)'
    required: false
    default: ''
  to:
    description: 'Commit SHA or HEAD as the last commit to include'
    required: true
  labels:
    description: 'Comma separated labels that will be added to all PRs and related issues'
    required: true
  color:
    description: 'The hexadecimal color code for new labels, without the leading `#`. Example: ff00ff'
    required: false
    default: 'aaaaaa'
outputs:
  issues:
    description: 'Issue ids in JSON format that were labeled. Example: [2, 3, 10, 12]'
runs:
  using: 'node16'
  main: 'dist/index.js'
